Repository SWEasabi/verbali, pull requests merged in 2023-02, with the labels that each got.

#28 Aggiunta date verbali mancanti
  interni/VIN_20221104/contenuti/info-generali.tex
  interni/VIN_20221104/d_VIN_20221104.tex
  interni/VIN_20221122_1/contenuti/info-generali.tex
  interni/VIN_20221122_1/d_VIN_20221122_1.tex
Labels: riunioni_interne, riunioni_esterne, sprint

#29 Close #26 - verbalizzazione vin_20221219
  interni/VIN_20221219/config.tex
  interni/VIN_20221219/contenuti/info-generali.tex
  interni/VIN_20221219/contenuti/ordine_del_giorno.tex
  interni/VIN_20221219/contenuti/svolgimento.tex
  interni/VIN_20221219/d_VIN_20221219.tex
  sprint/SPR_20230101/contenuti/ruoli.tex
Labels: riunioni_interne

#33 Risolto bug
  esterni/VEX_20221025/d_VEX_20221025.tex
Labels: bug, riunioni_esterne

#35 Feature/vex 20230214
  esterni/VEX_20230214/config.tex
  esterni/VEX_20230214/contenuti/discussione-finale.tex
  esterni/VEX_20230214/contenuti/img/bozza_architettura.png
  esterni/VEX_20230214/contenuti/info-generali.tex
  esterni/VEX_20230214/contenuti/ricevimento.tex
  esterni/VEX_20230214/d_VEX_20230214.tex
Labels: riunioni_esterne

#36 Feature/vin 20230111
  interni/VIN_20230111/config.tex
  interni/VIN_20230111/contenuti/info-generali.tex
  interni/VIN_20230111/contenuti/ordine_del_giorno.tex
  interni/VIN_20230111/contenuti/svolgimento.tex
  interni/VIN_20230111/d_VIN_20230111.tex
Labels: riunioni_interne
